<?php
require("../../head.phtml");
?>

<main class="new-repo-wrap">
    <h2 class="repo-name">Create a new repository</h2>

    <form class="new-repo" method="post">
        <div class="new-repo-name">
            <label for="name">Repository name</label>
            <input title="a-Z 0-9" pattern="[a-zA-Z0-9 -]{3,32}" type="text" name="name" id="name" required>
        </div>

        <div class="new-repo-vis">
            <label for="private">
                <svg aria-hidden="true" height="24" viewBox="0 0 16 16" version="1.1" width="24" data-view-component="true">
                    <path d="M4 4a4 4 0 0 1 8 0v2h.25c.966 0 1.75.784 1.75 1.75v5.5A1.75 1.75 0 0 1 12.25 15h-8.5A1.75 1.75 0 0 1 2 13.25v-5.5C2 6.784 2.784 6 3.75 6H4Zm8.25 3.5h-8.5a.25.25 0 0 0-.25.25v5.5c0 .138.112.25.25.25h8.5a.25.25 0 0 0 .25-.25v-5.5a.25.25 0 0 0-.25-.25ZM10.5 6V4a2.5 2.5 0 1 0-5 0v2Z"></path>
                </svg>

                Private

                <input type="radio" value="1" name="private" id="private">
                <span class="checkmark"></span>
            </label>

            <label for="public">
                <svg aria-hidden="true" height="24" viewBox="0 0 16 16" version="1.1" width="24" data-view-component="true"> 
                    <path d="M2 2.5A2.5 2.5 0 0 1 4.5 0h8.75a.75.75 0 0 1 .75.75v12.5a.75.75 0 0 1-.75.75h-2.5a.75.75 0 0 1 0-1.5h1.75v-2h-8a1 1 0 0 0-.714 1.7.75.75 0 1 1-1.072 1.05A2.495 2.495 0 0 1 2 11.5Zm10.5-1h-8a1 1 0 0 0-1 1v6.708A2.486 2.486 0 0 1 4.5 9h8ZM5 12.25a.25.25 0 0 1 .25-.25h3.5a.25.25 0 0 1 .25.25v3.25a.25.25 0 0 1-.4.2l-1.45-1.087a.249.249 0 0 0-.3 0L5.4 15.7a.25.25 0 0 1-.4-.2Z"></path>
                </svg>
                Public

                <input type="radio" value="0" checked name="private" id="public">
                <span class="checkmark"></span>
            </label>
        </div>

        <button type="submit">Create repository</button>
    </form>
</main>

</body>
</html>
