<?php
require("../../head.phtml");
?>

<h2>Create a new repository</h2>

<form method="post">
    <div>
        <label for="name">Repository name</label>
        <input type="text" name="name" id="name" required>
    </div>

    <div>
        <input type="radio" value="1" name="private" id="private">
        <label for="private">Private</label>

        <input type="radio" value="0" checked name="private" id="public">
        <label for="public">Public</label>
    </div>

    <button type="submit">Create repository</button>
</form>

</body>

</html>