<?php
require("../head.phtml");
?>

<form method="post">
    <div>
        <label for="username">username</label>
        <input type="text" name="username" id="username" required>
    </div>

    <div>
        <label for="password">password</label>
        <input type="password" name="password" id="password" minlength="6" maxlength="32" required>
    </div>

    <div>
        <label for="password2">password again</label>
        <input type="password" name="password2" id="password2" minlength="6" maxlength="32" required>
    </div>

    <button type="submit">Register</button>
</form>

<p>
    <?= $status ?>
</p>

</body>
</html>