<?php
if (isset($_POST["search"]) && !empty($_POST["search"])) {
    $search = $_POST["search"];

    if ($logged_in && $_POST["s-type"] === "user") {
        header("Location: /search?q=user:$search");
        exit;
    }

    header("Location: /search?q=$search");
}
?>

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?= $title ?></title>
    <link rel="stylesheet" href="/css/global.css">

    <?php if (isset($css)) foreach ($css as $c): ?>
        <link rel="stylesheet" href="/css/<?= $c ?>.css">
    <?php endforeach; ?>

    <script src="/search.js" defer></script>
</head>

<body>
    <header>
        <nav class="main-nav">
            <ul>
                <li>
                    <form method="post" id="s-form">
                        <div class="s-wrap">
                            <input autocomplete="off" type="text" name="search" id="search" placeholder="search">

                            <div hidden class="s-types">
                                <div active=true class="s-type" id="t-all">
                                    <div class="s-icon-wrap">
                                        <svg class="s-icon" title="Search" height="14" viewBox="0 0 16 16" version="1.1" width="14" data-view-component="true">
                                            <path d="M10.68 11.74a6 6 0 0 1-7.922-8.982 6 6 0 0 1 8.982 7.922l3.04 3.04a.749.749 0 0 1-.326 1.275.749.749 0 0 1-.734-.215ZM11.5 7a4.499 4.499 0 1 0-8.997 0A4.499 4.499 0 0 0 11.5 7Z"></path>
                                        </svg>
                                    </div>

                                    <div class="s-type-text"></div>

                                    <div class="s-desc-wrap">
                                        <div class="s-desc">All</div>
                                    </div>
                                </div>

                                <?php if ($logged_in) : ?>
                                    <div class="s-type" id="t-user">
                                        <div class="s-icon-wrap">
                                            <svg class="s-icon" title="Search" height="14" viewBox="0 0 16 16" version="1.1" width="14" data-view-component="true">
                                                <path d="M10.68 11.74a6 6 0 0 1-7.922-8.982 6 6 0 0 1 8.982 7.922l3.04 3.04a.749.749 0 0 1-.326 1.275.749.749 0 0 1-.734-.215ZM11.5 7a4.499 4.499 0 1 0-8.997 0A4.499 4.499 0 0 0 11.5 7Z"></path>
                                            </svg>
                                        </div>

                                        <div class="s-type-text"></div>

                                        <div class="s-desc-wrap">
                                            <div class="s-desc">In this user</div>
                                        </div>
                                    </div>
                                <?php endif; ?>
                            </div>
                        </div>

                        <input hidden type="radio" value="user" name="s-type" id="r-user">
                        <input hidden checked type="radio" value="all" name="s-type" id="r-all">

                        <button hidden type="submit">search</button>
                    </form>
                </li>
                <li><a href="/">home</a></li>
                <?php if (!$logged_in) : ?>
                    <li><a href="/login">log in</a></li>
                <?php endif; ?>

                <?php if ($logged_in) : ?>
                    <li><a href="/logout">log out</a></li>
                <?php endif; ?>
            </ul>
        </nav>
    </header>
