<main>
    <div class="repo-tree-top">
        <?php if ($logged_in && $repo["username"] == $_SESSION["user"] && $latest) : ?>
            <a class="upload" href="/repo/upload/?name=<?= $repo["name"] ?>">
                Upload files
            </a>
        <?php endif; ?>

        <?php if ($path == "") : ?>
            <a class="download" href="/repo/download/?name=<?= $repo["name"] ?>&commit=<?= $commit ?>">
                <svg aria-hidden="true" height="16" viewBox="0 0 16 16" version="1.1" width="16" data-view-component="true">
                    <path d="M3.5 1.75v11.5c0 .09.048.173.126.217a.75.75 0 0 1-.752 1.298A1.748 1.748 0 0 1 2 13.25V1.75C2 .784 2.784 0 3.75 0h5.586c.464 0 .909.185 1.237.513l2.914 2.914c.329.328.513.773.513 1.237v8.586A1.75 1.75 0 0 1 12.25 15h-.5a.75.75 0 0 1 0-1.5h.5a.25.25 0 0 0 .25-.25V4.664a.25.25 0 0 0-.073-.177L9.513 1.573a.25.25 0 0 0-.177-.073H7.25a.75.75 0 0 1 0 1.5h-.5a.75.75 0 0 1 0-1.5h-3a.25.25 0 0 0-.25.25Zm3.75 8.75h.5c.966 0 1.75.784 1.75 1.75v3a.75.75 0 0 1-.75.75h-2.5a.75.75 0 0 1-.75-.75v-3c0-.966.784-1.75 1.75-1.75ZM6 5.25a.75.75 0 0 1 .75-.75h.5a.75.75 0 0 1 0 1.5h-.5A.75.75 0 0 1 6 5.25Zm.75 2.25h.5a.75.75 0 0 1 0 1.5h-.5a.75.75 0 0 1 0-1.5ZM8 6.75A.75.75 0 0 1 8.75 6h.5a.75.75 0 0 1 0 1.5h-.5A.75.75 0 0 1 8 6.75ZM8.75 3h.5a.75.75 0 0 1 0 1.5h-.5a.75.75 0 0 1 0-1.5ZM8 9.75A.75.75 0 0 1 8.75 9h.5a.75.75 0 0 1 0 1.5h-.5A.75.75 0 0 1 8 9.75Zm-1 2.5v2.25h1v-2.25a.25.25 0 0 0-.25-.25h-.5a.25.25 0 0 0-.25.25Z"></path>
                </svg>

                Download zip 
            </a>
        <?php elseif ($path != "" && $logged_in && $repo["username"] == $_SESSION["user"] && $latest): ?>
            <span class="delete open-modal-btn" data-modal="delete-dir">
                Remove directory 
            </span>

            <dialog class="modal remove-confirm" data-modal="delete-dir">
                <div class="modal-head">
                    <span>Remove <?= $_GET["path"] ?></span>

                    <button data-modal="delete-dir" class="close-btn">
                        <svg aria-hidden="true" height="16" viewBox="0 0 16 16" version="1.1" width="16" data-view-component="true">
                            <path d="M3.72 3.72a.75.75 0 0 1 1.06 0L8 6.94l3.22-3.22a.749.749 0 0 1 1.275.326.749.749 0 0 1-.215.734L9.06 8l3.22 3.22a.749.749 0 0 1-.326 1.275.749.749 0 0 1-.734-.215L8 9.06l-3.22 3.22a.751.751 0 0 1-1.042-.018.751.751 0 0 1-.018-1.042L6.94 8 3.72 4.78a.75.75 0 0 1 0-1.06Z"></path>
                        </svg>
                    </button>
                </div>

                <a class="delete-dir" href="/repo/delete/?name=<?= $repo["name"] ?>&path=<?= $_GET["path"] ?>">Remove directory</a> 
                <span class="close-btn cancel" data-modal="delete-dir">Cancel</span>
            </dialog>
        <?php endif; ?>
    </div>

    <table class="repo-tree">
        <tr>
            <?php if ($path == ""): ?>
                <th class="picture-head">
                    <a href="/user?name=<?= $commit_info["author"] ?>">
                        <div class="picture-wrap">
                            <img src="/images?user=<?= $commit_info["author"] ?>&v=small" alt="author-picture">
                        </div>
                    </a>
                </th>
                <th class="commit-head-msg"><a class="author-name" href="/user?name=<?= $commit_info["author"] ?>"><?= $commit_info["author"] ?></a> <a href="/repo/commit?name=<?= $repo["name"] ?>&commit=<?= $commit_info["full_hash"] ?>" class="msg"><?= $commit_info["msg"] ?></a></th>
                <th class="commit-head-date"></th>
                <th class="commits-head">
                    <a href="/repo/commit?name=<?= $repo["name"] ?>&commit=<?= $commit_info["full_hash"] ?>" class="hash"><?= $commit_info["short_hash"] ?></a> <a href="/repo/commit?name=<?= $repo["name"] ?>&commit=<?= $commit_info["full_hash"] ?>" class="date"><?= $commit_info["date"] ?></a>

                    <a href="/repo/commits/?name=<?= $repo["name"] ?><?= $commit_query ?>">
                        <svg aria-hidden="true" height="16" viewBox="0 0 16 16" version="1.1" width="16" data-view-component="true">
                            <path d="m.427 1.927 1.215 1.215a8.002 8.002 0 1 1-1.6 5.685.75.75 0 1 1 1.493-.154 6.5 6.5 0 1 0 1.18-4.458l1.358 1.358A.25.25 0 0 1 3.896 6H.25A.25.25 0 0 1 0 5.75V2.104a.25.25 0 0 1 .427-.177ZM7.75 4a.75.75 0 0 1 .75.75v2.992l2.028.812a.75.75 0 0 1-.557 1.392l-2.5-1A.751.751 0 0 1 7 8.25v-3.5A.75.75 0 0 1 7.75 4Z"></path>
                        </svg>

                        <span><?= $commit_count ?></span> commits
                    </a>
                </th>
            <?php else: ?>
                <th></th>
                <th class="name-head">Name</th>
                <th class="msg-head">Last commit message</th>
                <th class="date-head">Last commit date</th>
            <?php endif; ?>
        </tr>

        <?php foreach ($files as $file) : ?>
            <tr>
                <td>
                    <?php if ($file["type"] == "blob") : ?>
                        <svg aria-label="File" aria-hidden="true" height="16" viewBox="0 0 16 16" version="1.1" width="16" data-view-component="true" >
                            <path d="M2 1.75C2 .784 2.784 0 3.75 0h6.586c.464 0 .909.184 1.237.513l2.914 2.914c.329.328.513.773.513 1.237v9.586A1.75 1.75 0 0 1 13.25 16h-9.5A1.75 1.75 0 0 1 2 14.25Zm1.75-.25a.25.25 0 0 0-.25.25v12.5c0 .138.112.25.25.25h9.5a.25.25 0 0 0 .25-.25V6h-2.75A1.75 1.75 0 0 1 9 4.25V1.5Zm6.75.062V4.25c0 .138.112.25.25.25h2.688l-.011-.013-2.914-2.914-.013-.011Z"></path>
                        </svg>
                    <?php endif ?> 
                    
                    <?php if ($file["type"] == "tree") : ?>
                        <svg aria-label="Directory" aria-hidden="true" height="16" viewBox="0 0 16 16" version="1.1" width="16" data-view-component="true" >
                            <path d="M1.75 1A1.75 1.75 0 0 0 0 2.75v10.5C0 14.216.784 15 1.75 15h12.5A1.75 1.75 0 0 0 16 13.25v-8.5A1.75 1.75 0 0 0 14.25 3H7.5a.25.25 0 0 1-.2-.1l-.9-1.2C6.07 1.26 5.55 1 5 1H1.75Z"></path>
                        </svg>
                    <?php endif ?>
                </td>
                <td class="file-name"> 
                    <a href="/repo/<?= $file["type"] ?>?name=<?= $repo["name"] ?>&commit=<?= $commit ?>&path=<?= $path . $file["name"] ?>">
                        <?= $file["name"] ?>
                    </a>
                </td>
                <td class="commit-msg">
                    <a href="/repo/commit?name=<?= $repo["name"] ?>&commit=<?= $file["commit"] ?>">
                        <?= $file["msg"] ?>
                    </a>
                </td>
                <td>
                    <?= $file["date"] ?>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
</main>


</body>
</html>
