<?php
require("../head.phtml");
?>

<form class="login-form" method="post">
    <h2>Log in</h2>

    <div>
        <label for="username">username</label>
        <input type="text" name="username" id="username" required>
    </div>

    <div>
        <label for="password">password</label>
        <input type="password" name="password" id="password" required>
    </div>

    <button type="submit">Log in</button>

    <span>
        or
        <a href="/register">
            register
        </a>
    </span>
</form>

</body>
</html>