<?php
require("../head.phtml");
?>

<form method="post">
    <div>
        <label for="username">username</label>
        <input type="text" name="username" id="username" required>
    </div>

    <div>
        <label for="password">password</label>
        <input type="password" name="password" id="password" required>
    </div>

    <a href="/register">
        register
    </a>

    <button type="submit">Login</button>
</form>

</body>
</html>