<?php
require("../../head.phtml");
require("../repo_head.phtml");
?>

    <pre><code><?php foreach ($file as $line) echo htmlspecialchars($line) . "\n"; ?></code></pre>
</main>

<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/11.7.0/highlight.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/highlightjs-line-numbers.js/2.7.0/highlightjs-line-numbers.min.js"></script>
<script>
    hljs.highlightAll();
    hljs.initLineNumbersOnLoad();
</script>
</body>
</html>
