<?php
require("../../head.phtml");
require("../repo_head.phtml");
?>
    
<main>

    <?php if (is_binary($file)): ?>
        <div class="binary">
            <h2>Binary file</h2>
            <a href="/repo/download/?name=<?= $repo["name"] ?>&commit=<?= $commit ?>&path=<?= $path ?>">download</a>
        </div>
    <?php else: ?>
        <div class="code-wrap">
            <div class="blob-head">
                <span><?= count($file) ?> lines</span>    

                <div class="icons">
                    <?php if ($logged_in && $repo["username"] == $_SESSION["user"] && $latest): ?>
                        <span class="icon remove open-modal-btn" data-modal="delete-file">
                            <svg aria-hidden="true" focusable="false" role="img" viewBox="0 0 24 24" width="24" height="24" fill="currentColor" style="display: inline-block; user-select: none; vertical-align: text-bottom;">
                                <path d="M5 20a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V8h2V6h-4V4a2 2 0 0 0-2-2H9a2 2 0 0 0-2 2v2H3v2h2zM9 4h6v2H9zM8 8h9v12H7V8z"></path>
                                <path d="M9 10h2v8H9zm4 0h2v8h-2z"></path>
                            </svg>
                        </span>
                    <?php endif ?>

                    <a class="icon download" href="/repo/download/?name=<?= $repo["name"] ?>&commit=<?= $commit ?>&path=<?= $path ?>">

                        <svg aria-hidden="true" focusable="false" role="img" viewBox="0 0 16 16" width="16" height="16" fill="currentColor" style="display: inline-block; user-select: none; vertical-align: text-bottom;">
                            <path d="M2.75 14A1.75 1.75 0 0 1 1 12.25v-2.5a.75.75 0 0 1 1.5 0v2.5c0 .138.112.25.25.25h10.5a.25.25 0 0 0 .25-.25v-2.5a.75.75 0 0 1 1.5 0v2.5A1.75 1.75 0 0 1 13.25 14Z"></path>
                            <path d="M7.25 7.689V2a.75.75 0 0 1 1.5 0v5.689l1.97-1.969a.749.749 0 1 1 1.06 1.06l-3.25 3.25a.749.749 0 0 1-1.06 0L4.22 6.78a.749.749 0 1 1 1.06-1.06l1.97 1.969Z"></path>
                        </svg>
                    </a>
                </div>
            </div>

            <pre><code><?php foreach ($file as $line) echo htmlspecialchars($line) . "\n"; ?></code></pre>
        </div>
    <?php endif; ?>
    
    <dialog class="modal remove-confirm" data-modal="delete-file">
        <div class="modal-head">
            <span>Remove <?= $_GET["path"] ?></span>

            <button data-modal="delete-file" class="close-btn">
                <svg aria-hidden="true" height="16" viewBox="0 0 16 16" version="1.1" width="16" data-view-component="true">
                    <path d="M3.72 3.72a.75.75 0 0 1 1.06 0L8 6.94l3.22-3.22a.749.749 0 0 1 1.275.326.749.749 0 0 1-.215.734L9.06 8l3.22 3.22a.749.749 0 0 1-.326 1.275.749.749 0 0 1-.734-.215L8 9.06l-3.22 3.22a.751.751 0 0 1-1.042-.018.751.751 0 0 1-.018-1.042L6.94 8 3.72 4.78a.75.75 0 0 1 0-1.06Z"></path>
                </svg>
            </button>
        </div>

        <a class="delete-dir" href="/repo/delete/?name=<?= $repo["name"] ?>&path=<?= $_GET["path"] ?>">Remove file</a> 
        <span class="close-btn cancel" data-modal="delete-file">Cancel</span>
    </dialog>
</main>

<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/11.7.0/highlight.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/highlightjs-line-numbers.js/2.7.0/highlightjs-line-numbers.min.js"></script>
<script>
    hljs.highlightAll();
    hljs.initLineNumbersOnLoad();
</script>
</body>
</html>
