<?php
require("../../head.phtml");
require("../repo_head.phtml");
?>
    
    <p>    
        <a href="/repo/download/?name=<?= $repo["name"] ?>&commit=<?= $commit ?>&path=<?= $path ?>">
            download 
        </a>
    </p>

    <?php
        if (is_binary($file)) {
            echo "binary file";
        } else {
            echo "<pre><code>";
            foreach ($file as $line) echo htmlspecialchars($line) . "\n";
            echo "</code></pre>";
        }
    ?>
</main>

<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/11.7.0/highlight.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/highlightjs-line-numbers.js/2.7.0/highlightjs-line-numbers.min.js"></script>
<script>
    hljs.highlightAll();
    hljs.initLineNumbersOnLoad();
</script>
</body>
</html>
