<?php
require("../head.phtml");
?>

<main>
    <div class="user-settings-wrap">
        <div class="forms">
            <form class="settings-rename settings-user" method="post">
                <label for="name">Name</label>
                <input value="<?= $user["name"] ?>" type="text" id="name" name="name" required>

                <button type="submit">Update name</button>
            </form>

            <h3>Change password</h3>

            <form class="settings-rename settings-user" method="post">
                <label for="old_password">Old password</label>
                <input type="password" id="old_password" name="old_password" required>

                <label for="new_password">New password</label>
                <input type="password" id="new_password" name="new_password" required>

                <label for="confirm_password">Confirm new password</label>
                <input type="password" id="confirm_password" name="confirm_password" required>

                <p><?= $pswd_status ?></p>

                <button type="submit">Change password</button>
            </form>
        </div>

        <div class="picture-container">
            <label>Profile picture</label>

            <p><?= $img_status ?></p>

            <div class="picture-upload-wrap">
                <?php if ($profile_pic): ?>
                    <img src="/images?user=<?= $user["username"] ?>&v=full" alt="profile-picture">
                <?php else: ?>
                    Upload profile picture
                <?php endif; ?>

                <form method="post" enctype="multipart/form-data">
                    <input type="hidden" name="MAX_FILE_SIZE" value="<?= $max_file_size ?>">
                    <input type="file" accept="<?= implode(",", $allowed_types) ?>" id="picture" name="picture" hidden>
                </form>
            </div>
        </div>
    </div>
</main>

</body>
</html>
