<?php
require("../../head.phtml");
require("../repo_head.phtml");
?>

	<h3>Upload files</h3>
	
	<form method="post" enctype="multipart/form-data">
	    <div>
	        <label>choose files</label>
	        <input type="hidden" name="MAX_FILE_SIZE" value="<?= $max_file_size ?>">
	        <input type="file" name="files[]" id="files" multiple required>
	    </div>

        <div>
            <label for="message">message</label>
            <input type="text" name="message" id="message" required>
        </div>
	
	    <button type="submit">Commit changes</button>
	</form>
</main>

</body>
</html>
