<?php
require("../../head.phtml");
require("../repo_head.phtml");
?>
    
<main>
    <form method="get">
        <input type="text" name="q">
        <button type="submit" hidden></button>
    </form>

    <table>
        <tr>
            <th></th>
            <th></th>
        </tr>

        <?php foreach ($issues as $issue): ?>
            <tr>
                <td><?= $issue["name"] ?></td>
                <td><?= $issue["comment_count"] ?></td>
            </tr>
        <?php endforeach; ?>
    </table>
</main>
</body>
</html>
