<?php
require("../../head.phtml");
require("../repo_head.phtml");
?>

    <table>
        <?php foreach($commits as $commit) : ?>
            <tr>
                <td>
                    <a>
                        <?= $commit["msg"] ?>
                    </a>    
                </td>
                <td>
                    <a>
                        <?= $commit["short_hash"] ?>
                    </a>    
                </td>
                <td>
                <a href="/repo/tree?name=<?= $repo["name"] ?>&commit=<?= $commit["full_hash"] ?>&path=">
                        <>
                    </a>
                </td>
            </tr>
        <?php endforeach ?>
    </table>
</main>

</body>
</html>
