<?php
require("../../head.phtml");
require("../repo_head.phtml");
?>
    <?php foreach($commits as $group) : ?>
        <p><?= $group["date"] ?></p> 

        <?php foreach($group["commits"] as $commit) : ?>
            <div>
                <div>
                    <?= $commit["msg"] ?>
                </div>

                <?= $commit["short_hash"] ?>

                <a href="/repo/tree?name=<?= $repo["name"] ?>&commit=<?= $commit["full_hash"] ?>&path=">
                    <>
                </a>
            </div>
        <?php endforeach ?>
    <?php endforeach ?>
</main>

</body>
</html>
