<?php
require("../../head.phtml");
require("../repo_head.phtml");
?>

<main>
    <?php foreach($commits as $group) : ?>
        <p class="date">Commits on <?= $group["date"] ?></p> 

        <?php foreach($group["commits"] as $commit) : ?>
            <div class="commit">
                <div>
                    <?= $commit["msg"] ?>
                </div>

                <div>
                    <a class="diff-btn" href="/repo/commit?name=<?= $repo["name"] ?>&commit=<?= $commit["full_hash"] ?>"><?= $commit["short_hash"] ?></a>

                    <a class="tree-btn" href="/repo/tree?name=<?= $repo["name"] ?>&commit=<?= $commit["full_hash"] ?>&path=">
                        <svg aria-hidden="true" height="16" viewBox="0 0 16 16" version="1.1" width="16" data-view-component="true">
                            <path d="m11.28 3.22 4.25 4.25a.75.75 0 0 1 0 1.06l-4.25 4.25a.749.749 0 0 1-1.275-.326.749.749 0 0 1 .215-.734L13.94 8l-3.72-3.72a.749.749 0 0 1 .326-1.275.749.749 0 0 1 .734.215Zm-6.56 0a.751.751 0 0 1 1.042.018.751.751 0 0 1 .018 1.042L2.06 8l3.72 3.72a.749.749 0 0 1-.326 1.275.749.749 0 0 1-.734-.215L.47 8.53a.75.75 0 0 1 0-1.06Z"></path>
                        </svg>
                    </a>
                </div>
            </div>
        <?php endforeach ?>
    <?php endforeach ?>
</main>

</body>
</html>
